language: c
sudo: required
dist: trusty
cache: ccache
services:
  - docker
env:
  - TR_ARCH=local       GCOV=1
  - TR_ARCH=local       CLANG=1
  - TR_ARCH=alpine
  - TR_ARCH=asan
  - TR_ARCH=x86_64
  - TR_ARCH=armv7hf
  - TR_ARCH=aarch64
  - TR_ARCH=ppc64le
  - TR_ARCH=armv7hf     CLANG=1
  - TR_ARCH=aarch64     CLANG=1
  - TR_ARCH=ppc64le     CLANG=1
  - TR_ARCH=alpine      CLANG=1
script:
  - sudo make CCACHE=1 -C scripts/travis $TR_ARCH
after_success:
  - ccache -s
  - make -C scripts/travis after_success
group: deprecated-2017Q2
