language: c
os: linux
dist: bionic
cache: ccache
services:
  - docker
env:
  - TR_ARCH=local
  - TR_ARCH=local       CLANG=1
  - TR_ARCH=local       COMPAT_TEST=y
  - TR_ARCH=local       CLANG=1 COMPAT_TEST=y
  - TR_ARCH=x86_64
  - TR_ARCH=x86_64      CLANG=1
  - TR_ARCH=openj9-test
  - TR_ARCH=vagrant-fedora-no-vdso
jobs:
  include:
    - os: linux
      arch: amd64
      env: TR_ARCH=local
      dist: focal
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local CLANG=1
      dist: bionic
    - os: linux
      arch: s390x
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: arm64
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: arm64
      env: TR_ARCH=local CLANG=1
      dist: bionic
    - os: linux
      arch: arm64
      # This runs on aarch64 with 'setarch linux32'
      env: TR_ARCH=armv7hf
      dist: bionic
    - os: linux
      arch: arm64
      # This runs on aarch64 with 'setarch linux32'
      env: TR_ARCH=armv7hf     CLANG=1
      dist: bionic
    - os: linux
      arch: arm64
      env: TR_ARCH=fedora-rawhide
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=fedora-rawhide
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=podman-test
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=docker-test
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=docker-test DIST=xenial
      # On xenial it should be possible to test overlayfs;
      # broken on the latest bionic kernel
      dist: xenial
    - os: linux
      arch: amd64
      env: TR_ARCH=alpine      CLANG=1
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=alpine
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=centos
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=fedora-asan
      dist: bionic
    - env: TR_ARCH=local STREAM_TEST=1
  allow_failures:
    - env: TR_ARCH=docker-test
    - env: TR_ARCH=docker-test DIST=xenial
    - env: TR_ARCH=fedora-rawhide
    - env: TR_ARCH=local       GCOV=1
script:
  - sudo make CCACHE=1 -C scripts/travis $TR_ARCH
after_success:
  - ccache -s
  - make -C scripts/travis after_success
