language: c
os: linux
dist: bionic
cache: ccache
services:
  - docker
jobs:
  include:
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local CLANG=1
      dist: bionic
    - os: linux
      arch: s390x
      env: TR_ARCH=local
      dist: bionic
    - os: linux
      arch: arm64-graviton2
      env: TR_ARCH=local RUN_TESTS=1
      dist: focal
      group: edge
      virt: vm
    - os: linux
      arch: arm64-graviton2
      env: TR_ARCH=local CLANG=1 RUN_TESTS=1
      group: edge
      virt: vm
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=docker-test
      dist: bionic
    - os: linux
      arch: amd64
      env: TR_ARCH=docker-test DIST=xenial
      # On xenial it should be possible to test overlayfs;
      # broken on the latest bionic kernel
      dist: xenial
  allow_failures:
    - env: TR_ARCH=docker-test
    - env: TR_ARCH=docker-test DIST=xenial
    - env: TR_ARCH=local       GCOV=1
script:
  - sudo make CCACHE=1 -C scripts/ci $TR_ARCH
after_success:
  - ccache -s
  - make -C scripts/ci after_success
