name: Java Test

on: [push, pull_request]

# Cancel any preceding run on the pull request.
concurrency:
  group: java-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/criu-dev' }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Run Java Test
      run: sudo make -C scripts/ci java-test
