name: CRIU Image Streamer Test

on: [push, pull_request]

# Cancel any preceding run on the pull request.
concurrency:
  group: stream-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/criu-dev' }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Run CRIU Image Streamer Test
      run: sudo -E make -C scripts/ci local STREAM_TEST=1
